"use client";

type Economics = { scenario_id: string; optimized_npv_rub: number; simulated_npv_rub_mean: number; simulated_npv_rub_min: number; simulated_npv_rub_max: number; profitability_sign_changed: boolean };
type Validation = { scenario_id: string; year: number; seeds: number; optimized_service_fraction: number; simulated_service_fraction_mean: number; service_gap_percentage_points: number };
type Alternative = { target_service_fraction: number; achieved_min_service_fraction: number | null; same_investment_as_target: number | null; optimization: { status: string; diagnostic?: string | null; gap?: number | null; cashflow_rub?: Record<string, number> }; operational_validation?: Validation[]; operational_economics?: Economics[]; service_acceptance?: { status: string; reason: string } };
const fmt = (value: number) => new Intl.NumberFormat("ru-RU", { maximumFractionDigits: 1 }).format(value);
const money = (value: number) => fmt(value / 1_000_000) + " млн ₽";
export default function AlternativeDetails({ alternatives }: { alternatives: Alternative[] }) {
  if (!alternatives.length) return null;
  return <div className="alternative-details">{alternatives.map((item) => <section className="alternative-item" key={item.target_service_fraction}><div className="alternative-head"><strong>Цель {fmt(item.target_service_fraction * 100)}% обслуживания</strong><span>{item.optimization.status === "infeasible" ? "Недостижимо" : item.optimization.status === "feasible" ? "Допустимо без доказанного минимума" : item.optimization.status === "optimal" ? "Минимум CAPEX в модели" : item.optimization.status}</span></div>{item.optimization.diagnostic && <p>{item.optimization.diagnostic}</p>}{item.same_investment_as_target !== null && <p>Та же конфигурация инвестиций, что для цели {fmt(item.same_investment_as_target * 100)}%.</p>}{item.optimization.gap != null && <p>Разрыв решателя: {fmt(item.optimization.gap * 100)}%.</p>}{item.service_acceptance && <p>Сценарная приёмка: {item.service_acceptance.status} · {item.service_acceptance.reason}</p>}{Boolean(item.operational_validation?.length) && <div className="alternative-rows"><h4>Обслуживание по сценарию и году</h4>{item.operational_validation?.map((row) => <div key={row.scenario_id + row.year}><span>{row.scenario_id} · {row.year}</span><span>MILP {fmt(row.optimized_service_fraction * 100)}%</span><span>SimPy {fmt(row.simulated_service_fraction_mean * 100)}% · {row.seeds} seed</span><span>Разрыв {fmt(row.service_gap_percentage_points)} п.п.</span></div>)}</div>}{Boolean(item.operational_economics?.length) && <div className="alternative-rows"><h4>Сценарный NPV после симуляции</h4>{item.operational_economics?.map((row) => <div key={row.scenario_id}><span>{row.scenario_id}</span><span>MILP {money(row.optimized_npv_rub)}</span><span>SimPy {money(row.simulated_npv_rub_mean)}</span><span className={row.profitability_sign_changed ? "risk-text" : ""}>{row.profitability_sign_changed ? "Знак доходности меняется" : "Диапазон " + money(row.simulated_npv_rub_min) + " … " + money(row.simulated_npv_rub_max)}</span></div>)}</div>}</section>)}</div>;
}
